---
- hosts: rpi4
  vars:
    packages: true
    files_mountpoint: /files
    tm_mountpoint: /timemachine
  remote_user: bazilio
  become: yes
  tasks:

  - name: "install packages"
    apt:
      update_cache: no
      name:
        - mc
        - screen
        - ntpdate
        - tmux
        - aptitude
        - git
        - samba
        - smartmontools
        - ntpdate
        - htop
        - iotop
        - hdparm
        - transmission-daemon
        - transmission-cli
        - build-essential
        - libevent-dev
        - libssl-dev
        - libgcrypt-dev
        - libkrb5-dev
        - libpam0g-dev
        - libwrap0-dev
        - libdb-dev
        - libtdb-dev
        - libmariadbclient-dev
        - avahi-daemon
        - libavahi-client-dev
        - libacl1-dev
        - libldap2-dev
        - libcrack2-dev
        - systemtap-sdt-dev
        - libdbus-1-dev
        - libdbus-glib-1-dev
        - libglib2.0-dev
        - libio-socket-inet6-perl
        - tracker
        - libtracker-sparql-2.0-dev
        - libtracker-miner-2.0-dev
        - kodi
      state: latest

    tags:
      - packages
    when: packages

### s alias
  - name: "Add aliases to /etc/profile"
    blockinfile:
      path: /etc/profile
      insertafter: EOF
      block: |
        alias s='sudo su -'
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      backup: yes

### sudoers
  - name: "sudoers NOPASSWD"
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo\s'
      line: '%sudo ALL=(ALL)  NOPASSWD: ALL'

### users
  - name: "Create user"
    user:
      name: bazilio
      # password created with:
      # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
      password: $1$Ub9VzL9S$9TF/6iNcJp4j5VixhZksK0
      home: "/home/bazilio"
      comment: "Hello there"
      groups:
      - sudo
      - adm
      - dialout
      - cdrom
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - spi
      - i2c
      - gpio


  - name: "Create bazilio user .ssh folder"
    file:
      path: "/home/bazilio/.ssh"
      state: directory
      owner: bazilio
      group: bazilio
      mode: 0700


  - name: "Create bazilio user authorized_keys file"
    copy:
      dest: "/home/bazilio/.ssh/authorized_keys"
      src: ./files/authorized_keys.bazilio_user
      owner: bazilio
      group: bazilio
      mode: 0600


### boot config
  - name: Place /boot/config.txt
    copy:
      dest: "/boot/config.txt"
      src: ./files/boot/config.txt
      owner: root
      group: root
      mode: 0755

### rc.local
  - name: "Disable wireless in rc.local"
    blockinfile:
      path: /etc/rc.local
      insertbefore: "exit\ 0"
      block: |
        /usr/sbin/rfkill block 0
        /usr/sbin/rfkill block 1
      marker: "# {mark} ANSIBLE MANAGED BLOCK"

### mounts
  - name: "Create files mount folder"
    file: path="{{ files_mountpoint }}" state=directory mode=777 owner=nobody group=nogroup


  - name: "Create timemachine mount folder"
    file: path="{{ tm_mountpoint }}" state=directory mode=775 owner=nobody group=nogroup


  - name: "Mount /files"
    mount:
      path: "{{ files_mountpoint }}"
      src: UUID=f3aa8b9e-8549-4d28-b75d-600cb206c499
      fstype: ext4
      state: mounted
      opts: defaults,noatime

  - name: "Mount /timemachine"
    mount:
      path: "{{ tm_mountpoint }}"
      src: UUID=acf2e14c-dd55-4665-9cd3-61ec1ea99800
      fstype: ext4
      state: mounted
      opts: defaults,user_xattr


### Samba
  - name: "Render SMB config"
    template:
      dest: /etc/samba/smb.conf
      src: ./templates/smb.conf.j2
      backup: yes
      owner: root
      group: root
      mode: 0644
    register: smbconf
    tags:
      - samba

  - name: restart samba
    systemd:
      name: smbd.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: smbconf.changed
    tags:
      - samba


### Time Machine
  - name: "Install packages for Time Machine support"
    apt:
      name:
        - avahi-daemon
      state: present
    tags:
      - timemachine
    
  - name: "Render Netatalk config"
    template:
      dest: /usr/local/etc/afp.conf
      src: ./templates/afp.conf.j2
      backup: yes
      owner: root
      group: staff
      mode: 0644
    register: afp_conf
    tags:
      - timemachine

  - name: "Restart Netatalk service"
    systemd:
      name: netatalk.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: afp_conf.changed
    tags:
      - timemachine

### Transmission
  - name: "Set sysctl config for Transmission"
    template:
      dest: /etc/sysctl.d/20-transmission.conf
      src: ./templates/20-transmission.conf.j2
      owner: root
      group: root
    register: transmission_sysctl
    tags:
      - transmission

  - name: "Apply sysctl config for Transmission"
    command: "/sbin/sysctl -p"
    when: transmission_sysctl.changed
    tags:
      - transmission

  - name: "Render Transmission config"
    template:
      dest: /etc/transmission-daemon/settings.json
      src: ./templates/transmission.settings.json.j2
      backup: yes
      owner: debian-transmission
      group: debian-transmission
      mode: 0600
    register: transmission_conf
    tags:
      - transmission

  - name: "Create torrent upload folder"
    file: path="{{ files_mountpoint }}/upload" state=directory mode=777 owner=nobody group=nogroup

  - name: "Restart Transmission service"
    systemd:
      name: transmission-daemon.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: transmission_conf.changed or transmission_sysctl.changed
    tags:
      - transmission
