---
- hosts: rpi3
  vars:
    packages: true
    files_mountpoint: /files
    tm_mountpoint: /timemachine
  remote_user: bazilio
  become: yes
  tasks:

  - name: "install packages"
    apt:
      update_cache: no
      name:
        - mc
        - screen
        - ntpdate
        - tmux 
        - git
        - samba
        - smartmontools
        - ntpdate
        - htop
        - iotop
        - transmission-daemon
        - transmission-cli
      state: latest

    tags:
      - packages
    when: packages

### s alias
  - name: "Add aliases to /etc/profile"
    blockinfile:
      path: /etc/profile
      insertafter: EOF
      block: |
        alias s='sudo su -'
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      backup: yes



### users
  - name: "Create user"
    user:
      name: bazilio
      home: "/home/bazilio"
      comment: "Hello there"
      group: bazilio
      groups:
      - sudo
      - adm
      - dialout
      - cdrom
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - spi
      - i2c
      - gpio


  - name: "Create bazilio user .ssh folder"
    file:
      path: "/home/bazilio/.ssh"
      state: directory
      recurse: yes
      owner: bazilio
      group: bazilio
      mode: 0700


  - name: "Create bazilio user authorized_keys file"
    copy:
      dest: "/home/bazilio/.ssh/authorized_keys"
      src: ./files/authorized_keys.bazilio_user
      owner: bazilio
      group: bazilio
      mode: 0600


### boot config
  - name: Place /boot/config.txt
    copy:
      dest: "/boot/config.txt"
      src: ./files/boot/config.txt
      owner: root
      group: root
      mode: 0755


### mounts
  - name: "Create files mount folder"
    file: path="{{ files_mountpoint }}" state=directory mode=777 owner=nobody group=nogroup


  - name: "Create timemachine mount folder"
    file: path="{{ tm_mountpoint }}" state=directory mode=775 owner=nobody group=nogroup


  - name: "Mount /files"
    mount:
      path: "{{ files_mountpoint }}"
      src: UUID=f3aa8b9e-8549-4d28-b75d-600cb206c499
      fstype: ext4
      state: mounted
      opts: defaults,noatime

  - name: "Mount /timemachine"
    mount:
      path: "{{ tm_mountpoint }}"
      src: UUID=acf2e14c-dd55-4665-9cd3-61ec1ea99800
      fstype: ext4
      state: mounted
      opts: defaults,user_xattr


### Samba
  - name: "Render SMB config"
    template:
      dest: /etc/samba/smb.conf
      src: ./templates/smb.conf.j2
      backup: yes
      owner: root
      group: root
      mode: 0644
    register: smbconf
    tags:
      - samba

  - name: restart samba
    systemd:
      name: smbd.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: smbconf.changed
    tags:
      - samba


### Time Machine
  - name: "Install packages for Time Machine support"
    apt:
      name:
        - avahi-daemon
      state: present
    tags:
      - timemachine
    
  - name: "Render Netatalk config"
    template:
      dest: /usr/local/etc/afp.conf
      src: ./templates/afp.conf.j2
      backup: yes
      owner: root
      group: staff
      mode: 0644
    register: afp_conf
    tags:
      - timemachine

  - name: "Restart Netatalk service"
    systemd:
      name: netatalk.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: afp_conf.changed
    tags:
      - timemachine

### Transmission
  - name: "Set sysctl config for Transmission"
    template:
      dest: /etc/sysctl.d/20-transmission.conf
      src: ./templates/20-transmission.conf.j2
      owner: root
      group: root
    register: transmission_sysctl
    tags:
      - transmission

  - name: "Apply sysctl config for Transmission"
    command: "/sbin/sysctl -p"
    when: transmission_sysctl.changed
    tags:
      - transmission

  - name: "Render Transmission config"
    template:
      dest: /etc/transmission-daemon/settings.json
      src: ./templates/transmission.settings.json.j2
      backup: yes
      owner: debian-transmission
      group: debian-transmission
      mode: 0600
    register: transmission_conf
    tags:
      - transmission

  - name: "Create torrent upload folder"
    file: path="{{ files_mountpoint }}/upload" state=directory mode=777 owner=nobody group=nogroup

  - name: "Restart Transmission service"
    systemd:
      name: transmission-daemon.service
      daemon_reload: yes
      enabled: yes
      masked: no
      state: restarted
    when: transmission_conf.changed or transmission_sysctl.changed
    tags:
      - transmission
